# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_community_membership <- function(cliques, max_node) {
    .Call(`_FasterCliquePercolation_calculate_community_membership`, cliques, max_node)
}

create_edges_matrix_custom <- function(cliques) {
    .Call(`_FasterCliquePercolation_create_edges_matrix_custom`, cliques)
}

create_edges_matrix_intersect <- function(cliques) {
    .Call(`_FasterCliquePercolation_create_edges_matrix_intersect`, cliques)
}

create_edges_matrix_setdiff <- function(cliques) {
    .Call(`_FasterCliquePercolation_create_edges_matrix_setdiff`, cliques)
}

rcpp_hello_world <- function() {
    .Call(`_FasterCliquePercolation_rcpp_hello_world`)
}

